name=MicroAbot
version=0.1.0
author=wookjin-chung <mail@fribot.com>
maintainer=wookjin-chung <mail@fribot.com>
sentence=Arduino library for controlling the Tandem Robotics MicroAbot.
paragraph=MicroAbot library provides functions to interface with the Tandem Robotics micro:bit and Arduino Uno for educational robotics projects. It includes calibration, movement, and sensor control functionalities.
category=Robotics
url=https://github.com/wookjin-chung/Tandem_Robotics
architectures=avr
